fix incorrect chest UNQs, fix TR key logic
rickfay/z17-randomizer pull request #78
Opened 2024-08-16 19:49 UTC by randomsalience

This makes two small changes:
- Fixes a couple chests that have their unique ids swapped, so that the item that is supposed to go in one chest would instead go in the other.
- Fixes the key logic for the upper big chest in Turtle Rock, which should logically require 3 keys because the keys may be spent in other places.

2024-08-19 13:36 UTC, randomsalience commented
Added another logic fix: Require cracks to be open for bootsless 65s Hotfoot

2024-08-21 18:37 UTC, rickfay requested changes
The UNQ and Hotfoot Logic changes look good, but I need you to remove the change to Turtle Rock's logic (there's another comment with more info there).

2024-08-21 18:37 UTC, rickfay commented on randomizer/src/world/turtle.rs
That chest requiring only one key was actually intended, as doing so allows for it to be a key-locked-key that savvy players can skip (if they're paying attention).

This is also the reason the rando's filler algorithm should be considered as guaranteeing 100% Items are accessible -- as opposed to guaranteeing 100% Locations are reachable -- though in the future I do want to add options for both (as well as Beatable Only).

You'll see similar behavior for the Desert Palace 1F Big Chest, and... well, I was going to say the Dark Palace Bomb Bowling Chest, but looking at it now it's actually not following the pattern. That shouldn't cause issues for the players but it's inconsistent and does need to be changed. I can take care of that later, unless you want to tackle it.

2024-08-26 23:03 UTC, rickfay approved these changes

2024-08-26 23:07 UTC, merged